//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.16 at 11:02:34 AM MDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://www.AdvantageOnlineBanking.com/ShipEx/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package https.www_advantageonlinebanking_com.shipex;
